# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29a814b3e3075e20970fbb4072db40110071fbf154518cf501785f22c6ab29583f63b69e0b022b0aca4a1e49f7b3d912d2713bb93a910b6b162eeee5d716abad

test:
  secret_key_base: 1de75a8c464ffd65402f711ddfd938df3c5eb80357f96bc926952332c3dae5790199422134b113d86badb4349dbc3f21c4aff7af34ebc3e742172ee15e9b9a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
